### PR TITLE
Ver -02 of the draft

### PR DESCRIPTION
**Pull request by mjethanandani**
This merge request will track changes for -02 version of the draft.

### CODE REVIEW

**Comment by bhstark2** [comment]
In draft-ietf-babel-yang-model.xml:
       <t>Finally, for security two subtree are defined. The hmac subtree
        which refers to parameters related to HMAC security mechanism. The
        boolean flag apply-all indicates whether HMAC mechanism is applicable
        for all interfaces or just for interfaces listed in the leaf-list
        'interfaces'. The dtls subtree refers to parameters related to DTLS
        security mechanism. Similar to the HMAC mechanism, the boolean flag
        apply-all indicates whether DTLS mechanism is applicable for all
        interfaces or just for interfaces listed in the leaf-list
        'interfaces'.</t>

apply-all no longer exists as a parameter. Recommend rewording this to:

        <t>Finally, for security two subtree are defined to contain sets of
        HMAC keys and DTLS certificates. The hmac subtree
        contains keys used with the HMAC security mechanism. The
        boolean flag babel-hmac-default-apply indicates whether the set
        of HMAC keys is automatically applied to new interfaces. The dtls
        subtree contains certificates used with the DTLS
        security mechanism. Similar to the HMAC mechanism, the boolean flag
        babel-dtls-default-apply indicates whether the set of DTLS
        certificates is automatically applied to new interfaces.</t>

Rewording verbiage can also be impacted by whether we rename babel-hmac and babel-dtls (see 
https://github.com/bhstark2/babel-information-model/issues/20.

**Comment by bhstark2** [comment]
In Security Considerations, this needs to be completed. Should I take a stab at it?
      <t>These are the subtrees and data nodes and their
      sensitivity/vulnerability:</t>

**Comment by bhstark2** [comment]
choice metric {

After the Prague discussion, the calculated-metric and received-metric are not mutually exclusive, so I think the "choice" statement needs to be deleted (if I understand it correctly). I don't think the data modeling syntax needs to impose a constraint of forcing at least one to be non-NULL, since the Babel implementation can be expected to take care of this.

**Comment by mjethanandani** [comment]
> In draft-ietf-babel-yang-model.xml:
> Finally, for security two subtree are defined. The hmac subtree
> which refers to parameters related to HMAC security mechanism. The
> boolean flag apply-all indicates whether HMAC mechanism is applicable
> for all interfaces or just for interfaces listed in the leaf-list
> 'interfaces'. The dtls subtree refers to parameters related to DTLS
> security mechanism. Similar to the HMAC mechanism, the boolean flag
> apply-all indicates whether DTLS mechanism is applicable for all
> interfaces or just for interfaces listed in the leaf-list
> 'interfaces'.
> 
> apply-all no longer exists as a parameter. Recommend rewording this to:
> 
> ```
>     <t>Finally, for security two subtree are defined to contain sets of
>     HMAC keys and DTLS certificates. The hmac subtree
>     contains keys used with the HMAC security mechanism. The
>     boolean flag babel-hmac-default-apply indicates whether the set
>     of HMAC keys is automatically applied to new interfaces. The dtls
>     subtree contains certificates used with the DTLS
>     security mechanism. Similar to the HMAC mechanism, the boolean flag
>     babel-dtls-default-apply indicates whether the set of DTLS
>     certificates is automatically applied to new interfaces.</t>
> ```
> 
> Rewording verbiage can also be impacted by whether we rename babel-hmac and babel-dtls (see
> [bhstark2/babel-information-model#20](https://github.com/bhstark2/babel-information-model/issues/20).

Made the verbiage change. 

This does raise the interesting question of what HMAC key or DTLS certificate is used on an existing interface if these values are changed?

**Comment by mjethanandani** [comment]
> In Security Considerations, this needs to be completed. Should I take a stab at it?
> These are the subtrees and data nodes and their
> sensitivity/vulnerability:

Please do.

**Comment by mjethanandani** [comment]
> choice metric {
> 
> After the Prague discussion, the calculated-metric and received-metric are not mutually exclusive, so I think the "choice" statement needs to be deleted (if I understand it correctly). I don't think the data modeling syntax needs to impose a constraint of forcing at least one to be non-NULL, since the Babel implementation can be expected to take care of this.

Yes, your understanding is correct. I have removed the choice statement and made them two individual leafs. Also, it is not mandatory for one of them to be non-NULL. Besides, in YANG you cannot enforce something to be mandatory if they are read-only.

**Pull request merged**
